name       : python-itsdangerous
version    : 0.24
release    : 2
source     :
    - https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.24.tar.gz : cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519
license    : BSD-3-Clause
component  : programming.python
summary    : Various helpers to pass trusted data to untrusted environments and back.
description: |
    Various helpers to pass trusted data to untrusted environments and back.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
