name       : python-itsdangerous
version    : 2.1.2
release    : 7
source     :
    - https://pypi.io/packages/source/i/itsdangerous/itsdangerous-2.1.2.tar.gz : 5dbbc68b317e5e42f327f9021763545dc3fc3bfe22e6deb96aaf1fc38874156a
homepage   : https://palletsprojects.com/p/itsdangerous/
license    : BSD-3-Clause
component  : programming.python
summary    : Various helpers to pass data to untrusted environments and back
description: |
    Various helpers to pass data to untrusted environments and to get it back safe and sound. Data is cryptographically signed to ensure that a token has not been tampered with.
builddeps  :
    - python-freezegun
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
