name       : python-itsdangerous
version    : 1.1.0
release    : 4
source     :
    - https://pypi.io/packages/source/i/itsdangerous/itsdangerous-1.1.0.tar.gz : 321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19
license    : BSD-3-Clause
component  : programming.python
summary    : Various helpers to pass trusted data to untrusted environments and back.
description: |
    Various helpers to pass trusted data to untrusted environments and back.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
